# Generated by Django 4.0.5 on 2022-06-23 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='Created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='Updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
